### ISSUE TITLE
Method getCollection is not implemented for the requested resource.

### ISSUE THREAD

**Issue by comcduarte** [dotkernel/api-documentation#50]
In tutorial,

When using command to list cooks I get the following error
```
Method getCollection is not implemented for the requested resource.
```
Added function to BookHandler
```
public function getCollection(ServerRequestInterface $request): ResponseInterface
    {
        return $this->createdResponse($request, $this->bookService->getBooks());
    }
```
Then I received a subsequent error
```
{"error":{"messages":["[Semantical Error] line 0, col 57 near \u0027created desc\u0027: Error: Class Api\\Book\\Entity\\Book has no field or association named created"]}}
```
By removing the order by in getBooks function for BookRepository I was able to resolve the issue.  The database table does not contain a field called created.
```
        ->from(Book::class, 'book')
//         ->orderBy($filters['order'] ?? 'book.created', $filters['dir'] ?? 'desc')
        ->setFirstResult($page['offset'])
```

**Comment by cPintiuta** [comment]
Hi @comcduarte , 
Thank you for addressing this issue. 
The tutorial is a little bit outdated because between the creation of this tutorial and now Dotkernel suffered some changes. 
In the latest pull request #51 , the tutorial will reflect the latest changes.

Regarding this issue, the "updated" and "created" comes in the newest version of Dotkernel api through "TimestampsTrait" so be sure you have this trait in the "Book" entity and also the attribute "#[ORM\HasLifecycleCallbacks]"

after you will need to make another migration to reflect the changes. 

```
#[ORM\Entity(repositoryClass: BookRepository::class)]
#[ORM\Table("book")]
#[ORM\HasLifecycleCallbacks]
class Book extends AbstractEntity
{
    use TimestampsTrait;

    #[ORM\Column(name: "name", type: "string", length: 100)]
    protected string $name;

// code
}
```
