### ISSUE TITLE
missing page 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api-documentation#56]
google bot found a page that is missing 
404 
https://docs.dotkernel.org/api/v4/introduction/installation/

and a page with redirect
https://docs.dotkernel.org/admin/

**Comment by alexmerlin** [comment]
> google bot found a page that is missing
> 404
> https://docs.dotkernel.org/api/v4/introduction/installation/

The correct page for
https://docs.dotkernel.org/api/v4/introduction/installation/
is
https://docs.dotkernel.org/api-documentation/v4/introduction/introduction/

We used`api/v4` URLs before moving Dotkernel API documentation to a separate repo.
After switching to the new repo, we are using `api-documentation/v4` URLs.

So, I don't think that we need to fix this, because the old format URLs should disappear, they won't have their own content in the future and we don't want duplicate pages.

---

> and a page with redirect
> https://docs.dotkernel.org/admin/

For the same reason, we have 3 redirects:

- https://docs.dotkernel.org/api/ -> https://docs.dotkernel.org/api-documentation/
- https://docs.dotkernel.org/admin/ -> https://docs.dotkernel.org/admin-documentation/
- https://docs.dotkernel.org/frontend/ -> https://docs.dotkernel.org/frontend-documentation/

I created them so that if someone enters manually in the browser https://docs.dotkernel.org/api/, they don't see a 404 page, instead they are taken to the correct URL.

If you consider that we don't need the redirects either, I can remove them.
